### ISSUE TITLE
Autoscroll checkbox appears too high in GUI

### ISSUE THREAD

**Issue by mitchell-merry** [thisis2838/LiveSplit.DebugSpew#1]
Hi, this component is great, but I got this:
![screenshot of the debugspew component](https://i.imgur.com/QyvdUF3.png)

The error here is that the Auto Scroll checkbox appears too high in the GUI. On first install I recall it working, but after some debug started rolling in the checkbox moved.

Restarting livesplit fixed the bug and I haven't replicated it since.

Thank you for making this component by the way.

**Comment by mitchell-merry** [comment]
This happens when you resize the window

**Comment by thisis2838** [comment]
Fixed in 1.2.0
